CREATE SCHEMA IF NOT EXISTS PRODUCTS;
CREATE TABLE IF NOT EXISTS PRODUCTS.PRODUCT_CATEGRORIES(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100),
    CREATED_BY  VARCHAR(50),
    CREATED_DATETIME    TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  VARCHAR(50),
    UPDATED_DATETIME    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS PRODUCTS.PRODUCT(
	ID BIGSERIAL PRIMARY KEY,
	NAME varchar(255) NULL,
    CATEGRORIE_ID BIGINT,
    PROPERTIES JSON,
    CREATED_BY  VARCHAR(50),
    CREATED_DATETIME    TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  VARCHAR(50),
    UPDATED_DATETIME    TIMESTAMP WITH TIME ZONE,
	FOREIGN KEY (CATEGRORIE_ID) REFERENCES PRODUCTS.PRODUCT_CATEGRORIES(ID)
);