CREATE SCHEMA IF NOT EXISTS CONTENTS;

CREATE TABLE IF NOT EXISTS CONTENTS.CATEGRORY(
	ID BIGSERIAL PRIMARY KEY,
	NAME varchar(255) NULL,
    CREATED_BY  VARCHAR(50),
    CREATED_DATETIME    TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  VARCHAR(50),
    UPDATED_DATETIME    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS CONTENTS.POST(
	ID BIGSERIAL PRIMARY KEY,
	NAME varchar(255) NULL,
    CATEGRORY_ID BIGINT,
    PARAGRAPHS TEXT[],
    CREATED_BY  VARCHAR(50),
    CREATED_DATETIME    TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  VARCHAR(50),
    UPDATED_DATETIME    TIMESTAMP WITH TIME ZONE,
	FOREIGN KEY (CATEGRORY_ID) REFERENCES CONTENTS.CATEGRORY(ID)
);