spring:
#config upload file
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
      
#config redis
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000   
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: true
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
      
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.217:5432/sang-demo-uaa
    username: postgres
    password: 123456
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    
#config migration
  flyway:
    locations: classpath:postgressql/062020,classpath:postgressql/012021
    schemas: users,files
    baseline-on-migrate: true