swagger-url: ${swagger-url:localhost:8080}
#config pattern log console
logging:
  level:
    root: INFO
    org.springframework: INFO
    sang.uaa.com.vn: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %C - %msg%n"
    
#secret key generate token jwt
jwt:
  secret:
    sang
    
#config folder upload
file:
  upload:
    path: classpath:file
    
server:
  port: 9999
  servlet:
    context-path: /api
spring:
  profiles:
    active:
    - dev