swagger-url: ${api-url:localhost:9999}
#config pattern log console
logging:
  level:
    root: INFO
    org.springframework: INFO
    sang.uaa.com.vn: TRACE
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cloud.sleuth: trace
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %X{traceId:-} %X{spanId:-} ${PID:-} %C - %msg%n"
    
#secret key generate token jwt
jwt:
  secret:
    sang
    
#config folder upload
file:
  upload:
    path: ${UPLOAD_FILE:D:/uploads}
    
server:
  port: 9999
  servlet:
    context-path: /api
    
spring:
  application:
    name: uaa-service
#config upload file
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping_app

  #config redis
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000   
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: true
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
      
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:sang-uaa-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    
#config migration
  flyway:
    locations: classpath:postgressql/062020,classpath:postgressql/012021, classpath:postgressql/072021
    schemas: users,files
    baseline-on-migrate: true
  profiles:
    active:
    - local
---
spring:
  profiles: dev
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping_app

  #config redis
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000   
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        id.new_generator_mappings: true
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
      
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:sang-uaa-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    
#config migration
  flyway:
    locations: classpath:postgressql/062020,classpath:postgressql/012021, classpath:postgressql/072021
    schemas: users,files
    baseline-on-migrate: true