CREATE SCHEMA IF NOT EXISTS FILES;
CREATE TABLE IF NOT EXISTS FILES.FILE_STORAGE(
    ID BIGSERIAL PRIMARY KEY,
    FILE_NAME VARCHAR(100),
    FILE_TYPE VARCHAR(50),
    FILE_PATH VARCHAR(100),
    USER_ID INT,
    CREATED_BY  VARCHAR(50),
    CREATED_DATETIME    TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  VARCHAR(50),
    UPDATED_DATETIME    TIMESTAMP WITH TIME ZONE
);
ALTER TABLE FILES.FILE_STORAGE DROP CONSTRAINT IF EXISTS FILE_STORAGE_USER_ID;
ALTER TABLE FILES.FILE_STORAGE ADD CONSTRAINT FILE_STORAGE_USER_ID
FOREIGN KEY (USER_ID) REFERENCES USERS.USER (ID);

-------------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS student_id_seq;

CREATE TABLE IF NOT EXISTS ENTERPRISE.STUDENT(
	ID integer NOT NULL,
	NAME varchar(255) NULL,
    CREATED_DATETIME    TIMESTAMP WITH TIME ZONE,
    UPDATED_BY  VARCHAR(50),
    UPDATED_DATETIME    TIMESTAMP WITH TIME ZONE,
	CONSTRAINT STUDENT_PKEY PRIMARY KEY (id)
);

INSERT INTO USERS.ROLE(NAME) VALUES('ROLE_ADMIN');
INSERT INTO USERS.USER(USERNAME, PASSWORD, CREATED_BY, CREATED_DATETIME, UPDATED_DATETIME) VALUES('sang', '$2a$10$nOrqw5R7MZVMSyxPd8paT.wixYaIwjFWJkS6t.nlltBD2UQvV9K56', 'Anmonymus', '2020-10-25 22:00:56', '2020-10-25 22:00:56');
INSERT INTO USERS.USER_ROLE (USER_ID, ROLE_ID) VALUES(1, 1);